[modules]
autoload=yes
noload=chan_sip.so
noload=chan_iax2.so
noload=chan_skinny.so
noload=chan_mgcp.so
noload=chan_unistim.so
noload=chan_dahdi.so
noload=chan_console.so
noload=res_fax.so
noload=res_fax_spandsp.so
noload=app_voicemail.so
noload=res_ael_share.so
noload=pbx_ael.so
noload=app_system.so
noload=app_exec.so
noload=func_shell.so
