"""Manual / one-off invoices, item catalog, templates, documents, share links and email delivery.

Money is always recomputed on the server (invoicing_math). Drafts are edited here; ISSUING stays the
existing POST /invoices/{id}/send (status change + dunning schedule + revenue outbox entry), so finance
posting keeps its contract: revenue is posted from invoices only, on issue.
"""
from __future__ import annotations

import json
import logging
import uuid
from datetime import date, timedelta
from decimal import Decimal
from typing import Optional

from fastapi import APIRouter, Depends, Header, HTTPException, Query, Response, status
from fastapi.responses import HTMLResponse, JSONResponse
from sqlalchemy import func, select

from services.common.auth import AuthContext, get_auth_context
from services.billing import calc, delivery, doc_service as ds, document_render as render, invoicing_math as im
from services.billing.access import require, require_tier
from services.billing.database import get_session, next_invoice_number
from services.billing.models import Invoice
from services.billing.models_invoicing import (
    DocumentDeliveryEvent, DocumentShareLink, InvoiceItem, InvoiceMeta, InvoiceTemplate,
)
from services.billing.schemas_invoicing import (
    EmailRequest, InvoiceUpdate, ItemIn, ItemPatch, LineOrder, ManualInvoiceCreate, ReconcileRequest,
    ShareLinkRequest, TemplateIn, TemplatePatch,
)

logger = logging.getLogger("billing.invoice_documents")

router = APIRouter(tags=["Invoice documents"])

HTML_HEADERS = {"Content-Security-Policy": render.CSP, "X-Content-Type-Options": "nosniff",
                "Cache-Control": "no-store", "Referrer-Policy": "no-referrer"}


# ── serialisers ──────────────────────────────────────────────────────────────

def invoice_detail(inv: Invoice, meta: Optional[InvoiceMeta]) -> dict:
    total, paid = Decimal(inv.total_zar), Decimal(inv.amount_paid_zar or 0)
    return {
        "id": str(inv.id), "number": inv.number, "status": inv.status, "customer_id": str(inv.customer_id),
        "subscription_id": str(inv.subscription_id) if inv.subscription_id else None,
        "credit_note_of": str(inv.credit_note_of) if inv.credit_note_of else None,
        "issue_date": (meta.issue_date.isoformat() if meta and meta.issue_date else None),
        "due_date": inv.due_date.isoformat(),
        "lines": inv.line_items or [],
        "subtotal_zar": str(inv.subtotal_zar), "discount_total_zar": str(meta.discount_total_zar if meta else "0.00"),
        "vat_zar": str(inv.vat_zar), "total_zar": str(total), "amount_paid_zar": str(paid),
        "balance_zar": str(total - paid), "currency": "ZAR",
        "notes": inv.notes, "terms": meta.terms if meta else None, "po_number": meta.po_number if meta else None,
        "source_type": meta.source_type if meta else "subscription" if inv.subscription_id else None,
        "created_by": meta.created_by if meta else None,
        "template_id": str(meta.template_id) if meta and meta.template_id else None,
        "bill_to": (meta.bill_to if meta else None) or {},
        "quote_id": str(meta.quote_id) if meta and meta.quote_id else None,
        "created_at": inv.created_at.isoformat() if inv.created_at else None,
    }


def _check_catalog(session, tenant_id, lines) -> None:
    ids = {l.catalog_item_id for l in lines if l.catalog_item_id}
    if not ids:
        return
    found = set(session.execute(select(InvoiceItem.id).where(
        InvoiceItem.tenant_id == tenant_id, InvoiceItem.id.in_(ids))).scalars().all())
    if ids - found:
        raise HTTPException(422, "Unknown catalog_item_id")


async def enforce_discount(ctx: AuthContext, totals: dict) -> None:
    if im.discount_needs_admin(totals):
        await require(ctx, "admin")  # 403: "needs a billing admin role"


def editable_draft(inv: Invoice) -> None:
    if inv.status != "draft":
        raise HTTPException(409, "Only draft invoices can be edited")
    if inv.credit_note_of is not None:
        raise HTTPException(409, "A credit note cannot be edited")
    if inv.subscription_id is not None:
        raise HTTPException(409, "Subscription invoices are generated by billing and cannot be edited here")


def _apply_lines(inv: Invoice, meta: InvoiceMeta, lines: list, totals: dict) -> None:
    inv.line_items = lines
    inv.subtotal_zar, inv.vat_zar, inv.total_zar = totals["subtotal_zar"], totals["vat_zar"], totals["total_zar"]
    meta.discount_total_zar = totals["discount_total_zar"]


# ── manual invoices ──────────────────────────────────────────────────────────

@router.post("/invoices/manual", status_code=status.HTTP_201_CREATED, dependencies=[Depends(require_tier("clerk"))])
async def create_manual_invoice(body: ManualInvoiceCreate, ctx: AuthContext = Depends(get_auth_context)):
    """Create a DRAFT invoice from free-form lines. Totals are computed here; any client totals are ignored.
    A discount above BILLING_CLERK_MAX_DISCOUNT_PERCENT (default 20%) of the gross needs a billing admin."""
    lines, totals = im.build_lines(body.lines)
    await enforce_discount(ctx, totals)
    bill_to = body.bill_to.model_dump() if body.bill_to else await ds.customer_snapshot(ctx.tenant_id, body.customer_id)
    with get_session() as session:
        _check_catalog(session, ctx.tenant_id, body.lines)
        ds.require_template(session, ctx.tenant_id, body.template_id)
        tmpl = ds.get_template(session, ctx.tenant_id, body.template_id)
        issue = body.issue_date or calc.today_sast()
        due = body.due_date or issue + timedelta(days=tmpl.default_due_days if tmpl else 30)
        if due < issue:
            raise HTTPException(422, "due_date cannot be before issue_date")
        inv = Invoice(
            id=uuid.uuid4(), tenant_id=ctx.tenant_id, customer_id=body.customer_id,
            number=next_invoice_number(session, ctx.tenant_id), status="draft", amount_paid_zar=Decimal("0.00"),
            due_date=due, notes=body.notes, line_items=lines,
            subtotal_zar=totals["subtotal_zar"], vat_zar=totals["vat_zar"], total_zar=totals["total_zar"])
        session.add(inv)
        session.flush()
        meta = InvoiceMeta(
            invoice_id=inv.id, tenant_id=ctx.tenant_id, issue_date=issue, po_number=body.po_number,
            source_type=body.source_type, created_by=body.created_by or ds.actor_of(ctx), terms=body.terms,
            discount_total_zar=totals["discount_total_zar"], template_id=body.template_id, bill_to=bill_to or None)
        session.add(meta)
        session.flush()
        session.refresh(inv)
        return invoice_detail(inv, meta)


@router.put("/invoices/{invoice_id}", dependencies=[Depends(require_tier("clerk"))])
async def update_draft_invoice(invoice_id: uuid.UUID, body: InvoiceUpdate, ctx: AuthContext = Depends(get_auth_context)):
    """Edit a draft. Send only the fields to change; ``lines`` replaces ALL lines (totals recomputed)."""
    new_lines = totals = None
    if body.lines is not None:
        new_lines, totals = im.build_lines(body.lines)
        await enforce_discount(ctx, totals)
    with get_session() as session:
        inv = ds.load_invoice(session, ctx.tenant_id, invoice_id, lock=True)
        editable_draft(inv)
        meta = ds.get_meta(session, inv.id)
        if meta is None:  # a draft that predates the suite: adopt it
            meta = InvoiceMeta(invoice_id=inv.id, tenant_id=ctx.tenant_id, source_type="manual",
                               created_by=ds.actor_of(ctx), issue_date=calc.today_sast())
            session.add(meta)
        if body.lines is not None:
            _check_catalog(session, ctx.tenant_id, body.lines)
            _apply_lines(inv, meta, new_lines, totals)
        if body.template_id is not None:
            ds.require_template(session, ctx.tenant_id, body.template_id)
            meta.template_id = body.template_id
        if body.issue_date is not None:
            meta.issue_date = body.issue_date
        if body.due_date is not None:
            inv.due_date = body.due_date
        if (meta.issue_date or inv.due_date) and meta.issue_date and inv.due_date < meta.issue_date:
            raise HTTPException(422, "due_date cannot be before issue_date")
        if body.notes is not None:
            inv.notes = body.notes
        if body.terms is not None:
            meta.terms = body.terms
        if body.po_number is not None:
            meta.po_number = body.po_number
        if body.bill_to is not None:
            meta.bill_to = body.bill_to.model_dump()
        session.flush()
        session.refresh(inv)
        return invoice_detail(inv, meta)


@router.post("/invoices/{invoice_id}/duplicate", status_code=status.HTTP_201_CREATED,
             dependencies=[Depends(require_tier("clerk"))])
async def duplicate_invoice(invoice_id: uuid.UUID, ctx: AuthContext = Depends(get_auth_context)):
    """New DRAFT copying the lines, notes, terms and bill-to of an existing (non-credit-note) invoice."""
    with get_session() as session:
        src = ds.load_invoice(session, ctx.tenant_id, invoice_id)
        if src.credit_note_of is not None:
            raise HTTPException(409, "A credit note cannot be duplicated")
        smeta = ds.get_meta(session, src.id)
        raw = []
        for ln in render.normalise_lines(src.line_items or []):
            raw.append({"description": ln["description"], "quantity": ln["quantity"], "unit_price": ln["unit_price"],
                        "discount": ln["discount"], "discount_type": "amount",
                        "tax_rate": ln["tax_rate"], "catalog_item_id": None})
        raw = [r for r in raw if Decimal(str(r["quantity"])) > 0 and Decimal(str(r["unit_price"])) >= 0]
        if not raw:
            raise HTTPException(409, "Invoice has no lines that can be duplicated")
        lines, totals = im.build_lines(raw)
        tmpl = ds.get_template(session, ctx.tenant_id, smeta.template_id if smeta else None)
        issue = calc.today_sast()
        inv = Invoice(
            id=uuid.uuid4(), tenant_id=ctx.tenant_id, customer_id=src.customer_id,
            number=next_invoice_number(session, ctx.tenant_id), status="draft", amount_paid_zar=Decimal("0.00"),
            due_date=issue + timedelta(days=tmpl.default_due_days if tmpl else 30), notes=src.notes, line_items=lines,
            subtotal_zar=totals["subtotal_zar"], vat_zar=totals["vat_zar"], total_zar=totals["total_zar"])
        session.add(inv)
        session.flush()
        meta = InvoiceMeta(
            invoice_id=inv.id, tenant_id=ctx.tenant_id, issue_date=issue, po_number=smeta.po_number if smeta else None,
            source_type=(smeta.source_type if smeta else "manual"), created_by=ds.actor_of(ctx),
            terms=smeta.terms if smeta else None, discount_total_zar=totals["discount_total_zar"],
            template_id=smeta.template_id if smeta else None, bill_to=smeta.bill_to if smeta else None)
        session.add(meta)
        session.flush()
        session.refresh(inv)
        return invoice_detail(inv, meta)


@router.put("/invoices/{invoice_id}/lines/order", dependencies=[Depends(require_tier("clerk"))])
async def reorder_lines(invoice_id: uuid.UUID, body: LineOrder, ctx: AuthContext = Depends(get_auth_context)):
    """Reorder draft lines: ``order`` must list every existing line_id exactly once."""
    with get_session() as session:
        inv = ds.load_invoice(session, ctx.tenant_id, invoice_id, lock=True)
        editable_draft(inv)
        current = list(inv.line_items or [])
        ids = [l.get("line_id") for l in current]
        if any(i is None for i in ids):
            raise HTTPException(409, "This invoice has lines without ids; re-save its lines (PUT /invoices/{id}) first")
        if sorted(body.order) != sorted(ids):
            raise HTTPException(422, "order must contain every line_id exactly once")
        by_id = {l["line_id"]: l for l in current}
        inv.line_items = [by_id[i] for i in body.order]
        session.flush()
        return invoice_detail(inv, ds.get_meta(session, inv.id))


@router.get("/invoices/{invoice_id}/detail", dependencies=[Depends(require_tier("reader"))])
async def invoice_with_meta(invoice_id: uuid.UUID, ctx: AuthContext = Depends(get_auth_context)):
    """Invoice including the suite's extras (issue date, PO, terms, source, bill-to, quote link)."""
    with get_session() as session:
        inv = ds.load_invoice(session, ctx.tenant_id, invoice_id)
        return invoice_detail(inv, ds.get_meta(session, inv.id))


# ── item catalog ─────────────────────────────────────────────────────────────

def item_out(i: InvoiceItem) -> dict:
    return {"id": str(i.id), "name": i.name, "description": i.description, "unit_price_zar": str(i.unit_price_zar),
            "tax_rate": str(i.tax_rate), "category": i.category, "active": i.active}


@router.get("/invoice-items", dependencies=[Depends(require_tier("reader"))])
async def list_items(ctx: AuthContext = Depends(get_auth_context), q: Optional[str] = Query(None, max_length=100),
                     category: Optional[str] = None, active: Optional[bool] = None,
                     limit: int = Query(100, ge=1, le=500), offset: int = Query(0, ge=0)):
    with get_session() as session:
        stmt = select(InvoiceItem).where(InvoiceItem.tenant_id == ctx.tenant_id)
        if q:
            stmt = stmt.where(func.lower(InvoiceItem.name).like(f"%{q.lower().replace('%', '').replace('_', '')}%"))
        if category:
            stmt = stmt.where(InvoiceItem.category == category)
        if active is not None:
            stmt = stmt.where(InvoiceItem.active.is_(active))
        rows = session.execute(stmt.order_by(InvoiceItem.name).limit(limit).offset(offset)).scalars().all()
        return [item_out(r) for r in rows]


@router.post("/invoice-items", status_code=status.HTTP_201_CREATED, dependencies=[Depends(require_tier("clerk"))])
async def create_item(body: ItemIn, ctx: AuthContext = Depends(get_auth_context)):
    with get_session() as session:
        item = InvoiceItem(
            tenant_id=ctx.tenant_id, name=body.name.strip(), description=body.description,
            unit_price_zar=im.money(body.unit_price_zar),
            tax_rate=im.money(body.tax_rate if body.tax_rate is not None else im.default_vat_rate()),
            category=body.category, active=body.active)
        session.add(item)
        session.flush()
        return item_out(item)


def _item(session, tenant_id, item_id) -> InvoiceItem:
    item = session.execute(select(InvoiceItem).where(
        InvoiceItem.id == item_id, InvoiceItem.tenant_id == tenant_id)).scalar_one_or_none()
    if item is None:
        raise HTTPException(404, "Item not found")
    return item


@router.get("/invoice-items/{item_id}", dependencies=[Depends(require_tier("reader"))])
async def get_item(item_id: uuid.UUID, ctx: AuthContext = Depends(get_auth_context)):
    with get_session() as session:
        return item_out(_item(session, ctx.tenant_id, item_id))


@router.put("/invoice-items/{item_id}", dependencies=[Depends(require_tier("clerk"))])
@router.patch("/invoice-items/{item_id}", dependencies=[Depends(require_tier("clerk"))])
async def update_item(item_id: uuid.UUID, body: ItemPatch, ctx: AuthContext = Depends(get_auth_context)):
    with get_session() as session:
        item = _item(session, ctx.tenant_id, item_id)
        for field, value in body.model_dump(exclude_unset=True).items():
            if field in ("unit_price_zar", "tax_rate") and value is not None:
                value = im.money(value)
            if value is None and field in ("name", "unit_price_zar", "tax_rate", "active"):
                continue
            setattr(item, field, value)
        session.flush()
        return item_out(item)


@router.delete("/invoice-items/{item_id}", status_code=status.HTTP_204_NO_CONTENT,
               dependencies=[Depends(require_tier("admin"))])
async def delete_item(item_id: uuid.UUID, ctx: AuthContext = Depends(get_auth_context)):
    """Existing invoices keep their own line snapshots, so deleting a catalog item is safe."""
    with get_session() as session:
        session.delete(_item(session, ctx.tenant_id, item_id))
    return Response(status_code=204)


# ── templates ────────────────────────────────────────────────────────────────

def template_out(t: InvoiceTemplate) -> dict:
    d = render.template_to_dict(t)
    d.update({"id": str(t.id), "is_default": t.is_default})
    return d


def _template(session, tenant_id, template_id) -> InvoiceTemplate:
    t = session.execute(select(InvoiceTemplate).where(
        InvoiceTemplate.id == template_id, InvoiceTemplate.tenant_id == tenant_id).with_for_update()).scalar_one_or_none()
    if t is None:
        raise HTTPException(404, "Template not found")
    return t


def _clear_other_defaults(session, tenant_id, keep_id) -> None:
    for other in session.execute(select(InvoiceTemplate).where(
            InvoiceTemplate.tenant_id == tenant_id, InvoiceTemplate.is_default.is_(True),
            InvoiceTemplate.id != keep_id).with_for_update()).scalars().all():
        other.is_default = False


@router.get("/invoice-templates", dependencies=[Depends(require_tier("reader"))])
async def list_templates(ctx: AuthContext = Depends(get_auth_context)):
    with get_session() as session:
        rows = session.execute(select(InvoiceTemplate).where(InvoiceTemplate.tenant_id == ctx.tenant_id)
                               .order_by(InvoiceTemplate.created_at)).scalars().all()
        return [template_out(r) for r in rows]


@router.get("/invoice-templates/default", dependencies=[Depends(require_tier("reader"))])
async def default_template(ctx: AuthContext = Depends(get_auth_context)):
    """The template documents render with when none is chosen (built-in defaults if none is marked default)."""
    with get_session() as session:
        t = ds.get_template(session, ctx.tenant_id)
        return template_out(t) if t else {**render.safe_template(None), "id": None, "is_default": True, "builtin": True}


@router.post("/invoice-templates", status_code=status.HTTP_201_CREATED, dependencies=[Depends(require_tier("admin"))])
async def create_template(body: TemplateIn, ctx: AuthContext = Depends(get_auth_context)):
    with get_session() as session:
        first = session.execute(select(func.count(InvoiceTemplate.id)).where(
            InvoiceTemplate.tenant_id == ctx.tenant_id)).scalar_one() == 0
        t = InvoiceTemplate(tenant_id=ctx.tenant_id, **{**body.model_dump(exclude={"show_columns"}),
                                                        "show_columns": body.show_columns.model_dump()})
        t.is_default = bool(body.is_default or first)  # the first template is the default
        session.add(t)
        session.flush()
        if t.is_default:
            _clear_other_defaults(session, ctx.tenant_id, t.id)
        return template_out(t)


@router.get("/invoice-templates/{template_id}", dependencies=[Depends(require_tier("reader"))])
async def get_template_route(template_id: uuid.UUID, ctx: AuthContext = Depends(get_auth_context)):
    with get_session() as session:
        return template_out(_template(session, ctx.tenant_id, template_id))


@router.put("/invoice-templates/{template_id}", dependencies=[Depends(require_tier("admin"))])
@router.patch("/invoice-templates/{template_id}", dependencies=[Depends(require_tier("admin"))])
async def update_template(template_id: uuid.UUID, body: TemplatePatch, ctx: AuthContext = Depends(get_auth_context)):
    with get_session() as session:
        t = _template(session, ctx.tenant_id, template_id)
        for field, value in body.model_dump(exclude_unset=True).items():
            if value is None and field in ("name", "accent_colour", "default_due_days", "show_columns",
                                           "show_payment_details", "show_terms", "is_default"):
                continue
            setattr(t, field, value)
        session.flush()
        if t.is_default:
            _clear_other_defaults(session, ctx.tenant_id, t.id)
        return template_out(t)


@router.delete("/invoice-templates/{template_id}", status_code=status.HTTP_204_NO_CONTENT,
               dependencies=[Depends(require_tier("admin"))])
async def delete_template(template_id: uuid.UUID, ctx: AuthContext = Depends(get_auth_context)):
    with get_session() as session:
        session.delete(_template(session, ctx.tenant_id, template_id))
    return Response(status_code=204)


# ── documents / exports ──────────────────────────────────────────────────────

def export_response(view: dict, fmt: str, filename: str):
    if fmt == "html":
        return HTMLResponse(render.render_html(view), headers=HTML_HEADERS)
    if fmt == "json":
        return JSONResponse(render.view_to_json(view), headers={"Cache-Control": "no-store"})
    if fmt == "csv":
        return Response(render.render_csv(view), media_type="text/csv; charset=utf-8", headers={
            "Content-Disposition": f'attachment; filename="{filename}.csv"', "X-Content-Type-Options": "nosniff",
            "Cache-Control": "no-store"})
    raise HTTPException(422, "format must be csv, json or html")


def _safe_filename(number: str) -> str:
    return "".join(c for c in number if c.isalnum() or c in "-_")[:60] or "document"


@router.get("/invoices/{invoice_id}/document", response_class=HTMLResponse, dependencies=[Depends(require_tier("reader"))])
async def invoice_document(invoice_id: uuid.UUID, ctx: AuthContext = Depends(get_auth_context)):
    """Print-ready, self-contained HTML (no scripts). Use the browser's print dialog for PDF."""
    with get_session() as session:
        view = ds.invoice_document(session, ctx.tenant_id, ds.load_invoice(session, ctx.tenant_id, invoice_id))
    return HTMLResponse(render.render_html(view), headers=HTML_HEADERS)


@router.get("/invoices/{invoice_id}/export", dependencies=[Depends(require_tier("reader"))])
async def invoice_export(invoice_id: uuid.UUID, ctx: AuthContext = Depends(get_auth_context),
                         format: str = Query("json")):
    with get_session() as session:
        inv = ds.load_invoice(session, ctx.tenant_id, invoice_id)
        view = ds.invoice_document(session, ctx.tenant_id, inv)
        name = _safe_filename(inv.number)
    return export_response(view, format.lower(), name)


# ── share links ──────────────────────────────────────────────────────────────

def link_out(l: DocumentShareLink) -> dict:
    now = ds.utcnow()
    return {"id": str(l.id), "doc_type": l.doc_type, "doc_id": str(l.doc_id),
            "expires_at": ds.aware(l.expires_at).isoformat(),
            "revoked_at": ds.aware(l.revoked_at).isoformat() if l.revoked_at else None,
            "active": l.revoked_at is None and ds.aware(l.expires_at) > now,
            "view_count": l.view_count, "last_viewed_at": ds.aware(l.last_viewed_at).isoformat() if l.last_viewed_at else None,
            "created_by": l.created_by}


def create_link_response(ctx: AuthContext, doc_type: str, doc_id: uuid.UUID, ttl: Optional[int]) -> dict:
    with get_session() as session:
        token, row = ds.mint_link(session, ctx.tenant_id, doc_type, doc_id, ds.actor_of(ctx), ttl)
        return ds.link_payload(token, row)


@router.post("/invoices/{invoice_id}/share-link", status_code=status.HTTP_201_CREATED,
             dependencies=[Depends(require_tier("clerk"))])
async def create_invoice_share_link(invoice_id: uuid.UUID, body: ShareLinkRequest = ShareLinkRequest(),
                                    ctx: AuthContext = Depends(get_auth_context)):
    """Mint a public view/pay link. The raw token is returned ONCE; only its hash is stored."""
    with get_session() as session:
        inv = ds.load_invoice(session, ctx.tenant_id, invoice_id)
        if inv.status == "draft":
            raise HTTPException(409, "Issue the invoice before sharing it")
        if inv.status == "voided":
            raise HTTPException(409, "A voided invoice cannot be shared")
    return create_link_response(ctx, "invoice", invoice_id, body.expires_in_days)


@router.get("/invoices/{invoice_id}/share-links", dependencies=[Depends(require_tier("reader"))])
async def list_invoice_share_links(invoice_id: uuid.UUID, ctx: AuthContext = Depends(get_auth_context)):
    with get_session() as session:
        ds.load_invoice(session, ctx.tenant_id, invoice_id)
        rows = session.execute(select(DocumentShareLink).where(
            DocumentShareLink.tenant_id == ctx.tenant_id, DocumentShareLink.doc_type == "invoice",
            DocumentShareLink.doc_id == invoice_id).order_by(DocumentShareLink.created_at.desc())).scalars().all()
        return [link_out(r) for r in rows]


@router.post("/share-links/{link_id}/revoke", dependencies=[Depends(require_tier("clerk"))])
async def revoke_share_link(link_id: uuid.UUID, ctx: AuthContext = Depends(get_auth_context)):
    with get_session() as session:
        row = session.execute(select(DocumentShareLink).where(
            DocumentShareLink.id == link_id, DocumentShareLink.tenant_id == ctx.tenant_id)).scalar_one_or_none()
        if row is None:
            raise HTTPException(404, "Link not found")
        if row.revoked_at is None:
            row.revoked_at = ds.utcnow()
        return link_out(row)


# ── email delivery ───────────────────────────────────────────────────────────

@router.post("/invoices/{invoice_id}/email", dependencies=[Depends(require_tier("clerk"))])
async def email_invoice(invoice_id: uuid.UUID, body: EmailRequest = EmailRequest(),
                        ctx: AuthContext = Depends(get_auth_context),
                        idempotency_key: Optional[str] = Header(None, alias="Idempotency-Key", max_length=128)):
    """Email an ISSUED invoice (document + signed view/pay link) via the Communication service.
    ``kind: "reminder"`` sends a payment reminder instead. 409 if a previous send is unconfirmed."""
    return await delivery.send_document_email(ctx=ctx, doc_type="invoice", doc_id=invoice_id, body=body,
                                              idempotency_key=idempotency_key)


@router.get("/invoices/{invoice_id}/delivery-events", dependencies=[Depends(require_tier("reader"))])
async def invoice_delivery_events(invoice_id: uuid.UUID, ctx: AuthContext = Depends(get_auth_context)):
    with get_session() as session:
        ds.load_invoice(session, ctx.tenant_id, invoice_id)
        return delivery_events_out(session, ctx.tenant_id, "invoice", invoice_id)


def delivery_events_out(session, tenant_id, doc_type, doc_id) -> list[dict]:
    rows = session.execute(select(DocumentDeliveryEvent).where(
        DocumentDeliveryEvent.tenant_id == tenant_id, DocumentDeliveryEvent.doc_type == doc_type,
        DocumentDeliveryEvent.doc_id == doc_id).order_by(DocumentDeliveryEvent.created_at)).scalars().all()
    return [{"id": str(r.id), "event_type": r.event_type, "kind": r.kind, "recipient": r.recipient,
             "subject": r.subject, "message_id": r.message_id, "actor": r.actor, "detail": r.detail,
             "at": ds.aware(r.created_at).isoformat() if r.created_at else None} for r in rows]


@router.post("/delivery/events/{event_id}/reconcile", dependencies=[Depends(require_tier("admin"))])
async def reconcile_delivery(event_id: uuid.UUID, body: ReconcileRequest, ctx: AuthContext = Depends(get_auth_context)):
    """Admin resolves an ambiguous (stuck ``queued``) send after checking the mailbox."""
    with get_session() as session:
        ev = session.execute(select(DocumentDeliveryEvent).where(
            DocumentDeliveryEvent.id == event_id, DocumentDeliveryEvent.tenant_id == ctx.tenant_id).with_for_update()
        ).scalar_one_or_none()
        if ev is None:
            raise HTTPException(404, "Delivery event not found")
        if ev.event_type != "queued":
            raise HTTPException(409, "Only a pending (queued) send can be reconciled")
        if body.outcome == "sent":
            ev.event_type = "sent"
            ev.message_id = (body.message_id or "").strip() or "manual-reconcile"
        else:
            ev.event_type = "failed"
            ev.idempotency_key = None
        ev.detail = {**(ev.detail or {}), "reconciled_by": ds.actor_of(ctx), "outcome": body.outcome}
        return {"id": str(ev.id), "event_type": ev.event_type, "message_id": ev.message_id}
