"""create purchasing and stock pipeline tables

Revision ID: f16015e33f34
Revises: 
Create Date: 2026-06-29 18:58:58.757688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f16015e33f34'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_sequences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.String(length=20), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'doc_type', name='uq_inventory_sequence_tenant_doctype')
    )
    op.create_index(op.f('ix_inventory_sequences_tenant_id'), 'inventory_sequences', ['tenant_id'], unique=False)
    op.create_table('inventory_service_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_service_type_tenant_code')
    )
    op.create_index(op.f('ix_inventory_service_types_tenant_id'), 'inventory_service_types', ['tenant_id'], unique=False)
    op.create_table('inventory_suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('payment_terms', sa.String(length=100), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_supplier_tenant_code')
    )
    op.create_index(op.f('ix_inventory_suppliers_tenant_id'), 'inventory_suppliers', ['tenant_id'], unique=False)
    op.create_table('inventory_warehouses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_external', sa.Boolean(), nullable=False),
    sa.Column('partner_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_warehouse_tenant_code')
    )
    op.create_index(op.f('ix_inventory_warehouses_tenant_id'), 'inventory_warehouses', ['tenant_id'], unique=False)
    op.create_table('inventory_product_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('service_type_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_type_id'], ['inventory_service_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_prod_category_tenant_code')
    )
    op.create_index(op.f('ix_inventory_product_categories_tenant_id'), 'inventory_product_categories', ['tenant_id'], unique=False)
    op.create_table('inventory_purchase_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'approved', 'partially_received', 'received', 'cancelled', name='po_status'), nullable=False),
    sa.Column('subtotal_zar', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_zar', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_zar', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_delivery', sa.Date(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['inventory_suppliers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inventory_warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'po_number', name='uq_po_tenant_number')
    )
    op.create_index(op.f('ix_inventory_purchase_orders_tenant_id'), 'inventory_purchase_orders', ['tenant_id'], unique=False)
    op.create_index('ix_po_supplier', 'inventory_purchase_orders', ['supplier_id'], unique=False)
    op.create_index('ix_po_tenant_status', 'inventory_purchase_orders', ['tenant_id', 'status'], unique=False)
    op.create_table('inventory_goods_receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('po_id', sa.UUID(), nullable=True),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('gr_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('pending', 'received', 'inspected', 'accepted', 'rejected', 'partially_accepted', name='gr_status'), nullable=False),
    sa.Column('received_by', sa.UUID(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inspected_by', sa.UUID(), nullable=True),
    sa.Column('inspected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supplier_delivery_note', sa.String(length=100), nullable=True),
    sa.Column('supplier_invoice_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['inventory_purchase_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inventory_warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'gr_number', name='uq_gr_tenant_number')
    )
    op.create_index('ix_gr_tenant_status', 'inventory_goods_receipts', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_inventory_goods_receipts_tenant_id'), 'inventory_goods_receipts', ['tenant_id'], unique=False)
    op.create_table('inventory_product_ranges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('download_speed_mbps', sa.Integer(), nullable=True),
    sa.Column('upload_speed_mbps', sa.Integer(), nullable=True),
    sa.Column('is_symmetrical', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['inventory_product_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_prod_range_tenant_code')
    )
    op.create_index(op.f('ix_inventory_product_ranges_tenant_id'), 'inventory_product_ranges', ['tenant_id'], unique=False)
    op.create_table('inventory_packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('service_type_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('range_id', sa.UUID(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('package_type', sa.Enum('fibre_bundle', 'lte_bundle', 'hardware_only', 'add_on', 'promotional', name='package_type'), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rrp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_sellable_standalone', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['inventory_product_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['range_id'], ['inventory_product_ranges.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_type_id'], ['inventory_service_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'sku', 'version', name='uq_package_tenant_sku_version')
    )
    op.create_index(op.f('ix_inventory_packages_tenant_id'), 'inventory_packages', ['tenant_id'], unique=False)
    op.create_index('ix_packages_effective', 'inventory_packages', ['effective_from', 'effective_to'], unique=False)
    op.create_index('ix_packages_hierarchy', 'inventory_packages', ['service_type_id', 'category_id', 'range_id'], unique=False)
    op.create_index('ix_packages_tenant_type', 'inventory_packages', ['tenant_id', 'package_type'], unique=False)
    op.create_table('inventory_goods_receipt_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gr_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity_ordered', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('quantity_accepted', sa.Integer(), nullable=False),
    sa.Column('quantity_rejected', sa.Integer(), nullable=False),
    sa.Column('unit_cost_zar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('serial_numbers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gr_id'], ['inventory_goods_receipts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['inventory_products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gri_gr', 'inventory_goods_receipt_items', ['gr_id'], unique=False)
    op.create_index('ix_gri_product', 'inventory_goods_receipt_items', ['product_id'], unique=False)
    op.create_table('inventory_package_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['inventory_packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['inventory_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_id', 'product_id', name='uq_package_item')
    )
    op.create_index('ix_package_items_product', 'inventory_package_items', ['product_id'], unique=False)
    op.create_table('inventory_pipeline_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=True),
    sa.Column('at_supplier', sa.Integer(), nullable=False),
    sa.Column('in_transit', sa.Integer(), nullable=False),
    sa.Column('in_warehouse', sa.Integer(), nullable=False),
    sa.Column('with_technicians', sa.Integer(), nullable=False),
    sa.Column('at_customer', sa.Integer(), nullable=False),
    sa.Column('in_return', sa.Integer(), nullable=False),
    sa.Column('total_value_zar', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['inventory_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inventory_warehouses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_pipeline_snapshots_tenant_id'), 'inventory_pipeline_snapshots', ['tenant_id'], unique=False)
    op.create_index('ix_pipeline_product', 'inventory_pipeline_snapshots', ['product_id'], unique=False)
    op.create_index('ix_pipeline_tenant_date', 'inventory_pipeline_snapshots', ['tenant_id', 'snapshot_date'], unique=False)
    op.create_table('inventory_pricing_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('package_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('pricing_type', sa.Enum('base', 'markup', 'markdown', 'promotional', 'clearance', 'bundle', name='pricing_type'), nullable=False),
    sa.Column('price_zar', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('markup_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('min_quantity', sa.Integer(), nullable=False),
    sa.Column('max_quantity', sa.Integer(), nullable=True),
    sa.Column('segment', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['inventory_packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['inventory_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_pricing_rules_tenant_id'), 'inventory_pricing_rules', ['tenant_id'], unique=False)
    op.create_index('ix_pricing_rules_tenant_package', 'inventory_pricing_rules', ['tenant_id', 'package_id'], unique=False)
    op.create_index('ix_pricing_rules_tenant_product', 'inventory_pricing_rules', ['tenant_id', 'product_id'], unique=False)
    op.create_index('ix_pricing_rules_valid', 'inventory_pricing_rules', ['valid_from', 'valid_to'], unique=False)
    op.create_table('inventory_purchase_order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('po_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity_ordered', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('unit_cost_zar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_cost_zar', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['inventory_purchase_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['inventory_products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_poi_po', 'inventory_purchase_order_items', ['po_id'], unique=False)
    op.create_index('ix_poi_product', 'inventory_purchase_order_items', ['product_id'], unique=False)
    op.create_table('inventory_stock_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.Enum('purchase_receipt', 'warehouse_transfer', 'technician_dispatch', 'technician_return', 'customer_dispatch', 'customer_return', 'adjustment', 'write_off', name='stock_movement_type'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('from_location_type', sa.String(length=30), nullable=True),
    sa.Column('from_location_id', sa.UUID(), nullable=True),
    sa.Column('to_location_type', sa.String(length=30), nullable=True),
    sa.Column('to_location_id', sa.UUID(), nullable=True),
    sa.Column('po_id', sa.UUID(), nullable=True),
    sa.Column('gr_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('technician_visit_id', sa.UUID(), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.Column('performed_by_type', sa.String(length=20), nullable=True),
    sa.Column('serial_numbers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gr_id'], ['inventory_goods_receipts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['po_id'], ['inventory_purchase_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['inventory_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_stock_movements_tenant_id'), 'inventory_stock_movements', ['tenant_id'], unique=False)
    op.create_index('ix_stock_move_from', 'inventory_stock_movements', ['from_location_type', 'from_location_id'], unique=False)
    op.create_index('ix_stock_move_product', 'inventory_stock_movements', ['product_id', 'created_at'], unique=False)
    op.create_index('ix_stock_move_tenant', 'inventory_stock_movements', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_stock_move_to', 'inventory_stock_movements', ['to_location_type', 'to_location_id'], unique=False)
    op.create_index('ix_stock_move_type', 'inventory_stock_movements', ['movement_type'], unique=False)
    op.create_table('inventory_technician_stocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('technician_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('safety_stock', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('in_transit', 'with_technician', 'returned', 'consumed', name='tech_stock_status'), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispatched_by', sa.UUID(), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('serial_numbers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['inventory_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inventory_warehouses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_technician_stocks_technician_id'), 'inventory_technician_stocks', ['technician_id'], unique=False)
    op.create_index(op.f('ix_inventory_technician_stocks_tenant_id'), 'inventory_technician_stocks', ['tenant_id'], unique=False)
    op.create_index('ix_tech_stock_product', 'inventory_technician_stocks', ['product_id'], unique=False)
    op.create_index('ix_tech_stock_status', 'inventory_technician_stocks', ['status'], unique=False)
    op.create_index('ix_tech_stock_tenant_tech', 'inventory_technician_stocks', ['tenant_id', 'technician_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tech_stock_tenant_tech', table_name='inventory_technician_stocks')
    op.drop_index('ix_tech_stock_status', table_name='inventory_technician_stocks')
    op.drop_index('ix_tech_stock_product', table_name='inventory_technician_stocks')
    op.drop_index(op.f('ix_inventory_technician_stocks_tenant_id'), table_name='inventory_technician_stocks')
    op.drop_index(op.f('ix_inventory_technician_stocks_technician_id'), table_name='inventory_technician_stocks')
    op.drop_table('inventory_technician_stocks')
    op.drop_index('ix_stock_move_type', table_name='inventory_stock_movements')
    op.drop_index('ix_stock_move_to', table_name='inventory_stock_movements')
    op.drop_index('ix_stock_move_tenant', table_name='inventory_stock_movements')
    op.drop_index('ix_stock_move_product', table_name='inventory_stock_movements')
    op.drop_index('ix_stock_move_from', table_name='inventory_stock_movements')
    op.drop_index(op.f('ix_inventory_stock_movements_tenant_id'), table_name='inventory_stock_movements')
    op.drop_table('inventory_stock_movements')
    op.drop_index('ix_poi_product', table_name='inventory_purchase_order_items')
    op.drop_index('ix_poi_po', table_name='inventory_purchase_order_items')
    op.drop_table('inventory_purchase_order_items')
    op.drop_index('ix_pricing_rules_valid', table_name='inventory_pricing_rules')
    op.drop_index('ix_pricing_rules_tenant_product', table_name='inventory_pricing_rules')
    op.drop_index('ix_pricing_rules_tenant_package', table_name='inventory_pricing_rules')
    op.drop_index(op.f('ix_inventory_pricing_rules_tenant_id'), table_name='inventory_pricing_rules')
    op.drop_table('inventory_pricing_rules')
    op.drop_index('ix_pipeline_tenant_date', table_name='inventory_pipeline_snapshots')
    op.drop_index('ix_pipeline_product', table_name='inventory_pipeline_snapshots')
    op.drop_index(op.f('ix_inventory_pipeline_snapshots_tenant_id'), table_name='inventory_pipeline_snapshots')
    op.drop_table('inventory_pipeline_snapshots')
    op.drop_index('ix_package_items_product', table_name='inventory_package_items')
    op.drop_table('inventory_package_items')
    op.drop_index('ix_gri_product', table_name='inventory_goods_receipt_items')
    op.drop_index('ix_gri_gr', table_name='inventory_goods_receipt_items')
    op.drop_table('inventory_goods_receipt_items')
    op.drop_index('ix_packages_tenant_type', table_name='inventory_packages')
    op.drop_index('ix_packages_hierarchy', table_name='inventory_packages')
    op.drop_index('ix_packages_effective', table_name='inventory_packages')
    op.drop_index(op.f('ix_inventory_packages_tenant_id'), table_name='inventory_packages')
    op.drop_table('inventory_packages')
    op.drop_index(op.f('ix_inventory_product_ranges_tenant_id'), table_name='inventory_product_ranges')
    op.drop_table('inventory_product_ranges')
    op.drop_index(op.f('ix_inventory_goods_receipts_tenant_id'), table_name='inventory_goods_receipts')
    op.drop_index('ix_gr_tenant_status', table_name='inventory_goods_receipts')
    op.drop_table('inventory_goods_receipts')
    op.drop_index('ix_po_tenant_status', table_name='inventory_purchase_orders')
    op.drop_index('ix_po_supplier', table_name='inventory_purchase_orders')
    op.drop_index(op.f('ix_inventory_purchase_orders_tenant_id'), table_name='inventory_purchase_orders')
    op.drop_table('inventory_purchase_orders')
    op.drop_index(op.f('ix_inventory_product_categories_tenant_id'), table_name='inventory_product_categories')
    op.drop_table('inventory_product_categories')
    op.drop_index(op.f('ix_inventory_warehouses_tenant_id'), table_name='inventory_warehouses')
    op.drop_table('inventory_warehouses')
    op.drop_index(op.f('ix_inventory_suppliers_tenant_id'), table_name='inventory_suppliers')
    op.drop_table('inventory_suppliers')
    op.drop_index(op.f('ix_inventory_service_types_tenant_id'), table_name='inventory_service_types')
    op.drop_table('inventory_service_types')
    op.drop_index(op.f('ix_inventory_sequences_tenant_id'), table_name='inventory_sequences')
    op.drop_table('inventory_sequences')
    # ### end Alembic commands ###
