import {
  AgentMailPod,
  AgentMailbox,
  AgentMailThread,
  AgentMailLabel,
  AgentMailListRule,
  AgentMailDomain,
  AgentMailMetrics,
  AgentMailPermission,
  SharedMailboxGroup,
  SharedMailFolder,
} from "./types"

export const INITIAL_PODS: AgentMailPod[] = [
  {
    id: "pod-default",
    name: "Default Pod",
    tenantId: "tenant-burni",
    isDefault: true,
    description: "Primary multi-tenant workspace pod for automated agent handling",
    inboxCount: 4,
    createdAt: "2026-08-15T08:00:00Z",
  },
  {
    id: "pod-enterprise",
    name: "OmniDome HQ Pod",
    tenantId: "tenant-hq",
    isDefault: false,
    description: "Corporate communications and executive approvals",
    inboxCount: 2,
    createdAt: "2026-09-01T10:30:00Z",
  },
  {
    id: "pod-sales",
    name: "Sales & Outreach Pod",
    tenantId: "tenant-burni",
    isDefault: false,
    description: "High volume outbound lead nurturing and inbound qualification",
    inboxCount: 2,
    createdAt: "2026-09-10T14:15:00Z",
  },
]

export const INITIAL_MAILBOXES: AgentMailbox[] = [
  {
    id: "mb-burnibraa",
    podId: "pod-default",
    emailAddress: "burnibraa@agentmail.to",
    displayName: "Burni Braai (Primary)",
    agentType: "auto_reply",
    isHuman: true,
    domain: "agentmail.to",
    autoReplyEnabled: true,
    smartLabelEnabled: true,
    inboundChannelId: "general",
    assignedUser: "Burni Braai",
    unreadCount: 2,
    totalCount: 5,
    isActive: true,
    createdAt: "2026-08-20T08:00:00Z",
  },
  {
    id: "mb-sales",
    podId: "pod-default",
    emailAddress: "sales@omnidome.co.za",
    displayName: "Sales Agent (OmniDome)",
    agentType: "sales",
    isHuman: false,
    domain: "omnidome.co.za",
    autoReplyEnabled: true,
    smartLabelEnabled: true,
    inboundChannelId: "sales-team",
    unreadCount: 3,
    totalCount: 18,
    isActive: true,
    createdAt: "2026-09-05T09:00:00Z",
  },
  {
    id: "mb-info",
    podId: "pod-default",
    emailAddress: "info@omnidome.co.za",
    displayName: "Smart Label Agent (Info)",
    agentType: "smart_label",
    isHuman: false,
    domain: "omnidome.co.za",
    autoReplyEnabled: true,
    smartLabelEnabled: true,
    inboundChannelId: "customer-support",
    unreadCount: 2,
    totalCount: 42,
    isActive: true,
    createdAt: "2026-09-05T09:15:00Z",
  },
  {
    id: "mb-finance",
    podId: "pod-default",
    emailAddress: "finance@omnidome.co.za",
    displayName: "Finance Agent",
    agentType: "finance",
    isHuman: false,
    domain: "omnidome.co.za",
    autoReplyEnabled: false,
    smartLabelEnabled: true,
    inboundChannelId: "finance-team",
    unreadCount: 1,
    totalCount: 9,
    isActive: true,
    createdAt: "2026-09-12T11:00:00Z",
  },
  {
    id: "mb-benedict",
    podId: "pod-default",
    emailAddress: "benedict@omnidome.co.za",
    displayName: "Benedict S. Majozi",
    agentType: "human",
    isHuman: true,
    domain: "omnidome.co.za",
    autoReplyEnabled: false,
    smartLabelEnabled: true,
    assignedUser: "Benedict",
    unreadCount: 0,
    totalCount: 12,
    isActive: true,
    createdAt: "2026-09-01T08:00:00Z",
  },
]

export const INITIAL_SHARED_GROUPS: SharedMailboxGroup[] = [
  {
    id: "grp-sales",
    mailboxId: "mb-sales",
    name: "Enterprise Sales Team",
    emailAddress: "sales@omnidome.co.za",
    description: "Shared mailbox for incoming B2B enterprise leads, quotes, and pilot requests.",
    members: [
      {
        userId: "usr-burni",
        name: "Burni Braai",
        email: "burnibraa@gmail.com",
        role: "admin",
        avatar: "B",
        addedAt: "2026-08-15T08:00:00Z",
      },
      {
        userId: "usr-benedict",
        name: "Benedict S. Majozi",
        email: "benedict@omnidome.co.za",
        role: "admin",
        avatar: "BM",
        addedAt: "2026-09-01T09:00:00Z",
      },
      {
        userId: "usr-sarah",
        name: "Sarah Chen",
        email: "sarah.chen@omnidome.co.za",
        role: "operator",
        avatar: "SC",
        addedAt: "2026-09-03T10:00:00Z",
      },
    ],
    assignedAgents: ["sales", "auto_reply"],
    sharedFolders: ["Inbound Leads", "Dispatched Quotes", "High Intent Pipeline", "Escalations"],
    inboundChannelId: "sales-team",
    autoReplyApprovalRequired: true,
    escalationChannel: "#sales-escalations",
    unreadCount: 3,
    totalCount: 18,
  },
  {
    id: "grp-info",
    mailboxId: "mb-info",
    name: "General Inquiries & Support",
    emailAddress: "info@omnidome.co.za",
    description: "Customer service triage, ticket routing, and community relations.",
    members: [
      {
        userId: "usr-burni",
        name: "Burni Braai",
        email: "burnibraa@gmail.com",
        role: "admin",
        avatar: "B",
        addedAt: "2026-08-15T08:00:00Z",
      },
      {
        userId: "usr-sipho",
        name: "Sipho Sithole",
        email: "sipho@omnidome.co.za",
        role: "operator",
        avatar: "SS",
        addedAt: "2026-09-05T11:00:00Z",
      },
      {
        userId: "usr-elena",
        name: "Elena Rostova",
        email: "elena@omnidome.co.za",
        role: "member",
        avatar: "ER",
        addedAt: "2026-09-06T14:30:00Z",
      },
      {
        userId: "usr-benedict",
        name: "Benedict S. Majozi",
        email: "benedict@omnidome.co.za",
        role: "viewer",
        avatar: "BM",
        addedAt: "2026-09-01T09:00:00Z",
      },
    ],
    assignedAgents: ["smart_label", "auto_reply", "support"],
    sharedFolders: ["Customer Support", "Network Incident Tickets", "Vendor Inquiries"],
    inboundChannelId: "customer-support",
    autoReplyApprovalRequired: false,
    escalationChannel: "#ops-alerts",
    unreadCount: 2,
    totalCount: 42,
  },
  {
    id: "grp-finance",
    mailboxId: "mb-finance",
    name: "Finance & Settlements",
    emailAddress: "finance@omnidome.co.za",
    description: "Invoicing, remittances, carrier billing settlement, and audit receipts.",
    members: [
      {
        userId: "usr-burni",
        name: "Burni Braai",
        email: "burnibraa@gmail.com",
        role: "admin",
        avatar: "B",
        addedAt: "2026-08-15T08:00:00Z",
      },
      {
        userId: "usr-benedict",
        name: "Benedict S. Majozi",
        email: "benedict@omnidome.co.za",
        role: "operator",
        avatar: "BM",
        addedAt: "2026-09-01T09:00:00Z",
      },
    ],
    assignedAgents: ["finance"],
    sharedFolders: ["Remittances", "Overdue Invoices", "Tax & Audit"],
    inboundChannelId: "finance-team",
    autoReplyApprovalRequired: true,
    escalationChannel: "#executive-finance",
    unreadCount: 1,
    totalCount: 9,
  },
]

export const INITIAL_SHARED_FOLDERS: SharedMailFolder[] = [
  {
    id: "folder-inbound-leads",
    name: "Enterprise Leads",
    mailboxId: "mb-sales",
    icon: "Folder",
    threadCount: 12,
    members: ["Burni Braai", "Benedict Majozi", "Sarah Chen"],
  },
  {
    id: "folder-quotes",
    name: "Dispatched Proposals",
    mailboxId: "mb-sales",
    icon: "FileText",
    threadCount: 6,
    members: ["Burni Braai", "Sarah Chen"],
  },
  {
    id: "folder-support-tickets",
    name: "Support Incident Tickets",
    mailboxId: "mb-info",
    icon: "AlertCircle",
    threadCount: 18,
    members: ["Burni Braai", "Sipho Sithole", "Elena Rostova"],
  },
  {
    id: "folder-remittance",
    name: "EFT Remittances",
    mailboxId: "mb-finance",
    icon: "Shield",
    threadCount: 7,
    members: ["Burni Braai", "Benedict Majozi"],
  },
]

export const INITIAL_THREADS: AgentMailThread[] = [
  // 1. Alex Nurzi (Firecrawl) - Exact match from screenshot media_1790515130371.png
  {
    id: "thread-alex-nurzi",
    podId: "pod-default",
    mailboxId: "mb-burnibraa",
    sender: "Alex Nurzi",
    senderEmail: "alex@firecrawl.dev",
    recipientEmail: "burnibraa@agentmail.to",
    subject: "Get the most out of Firecrawl",
    snippet: "Hey Burni, welcome to Firecrawl! Here are three quick patterns to extract pristine markdown from modern dynamic websites...",
    unread: false,
    isStarred: true,
    folder: "inbox",
    labels: ["Verified Senders", "Developer API"],
    assignedAgent: "auto_reply",
    messagesCount: 1,
    hasAttachments: false,
    dateGroup: "Sep 27",
    timestamp: "2:56 AM",
    aiAnalysis: {
      sentiment: "positive",
      category: "Developer Tooling",
      confidence: 0.99,
      suggestedAction: "none",
      notes: "Onboarding email from Firecrawl MCP integration. Auto-indexed documentation references.",
    },
    messages: [
      {
        id: "msg-alex-1",
        threadId: "thread-alex-nurzi",
        direction: "inbound",
        sender: "Alex Nurzi",
        senderEmail: "alex@firecrawl.dev",
        recipient: "Burni Braai",
        recipientEmail: "burnibraa@agentmail.to",
        subject: "Get the most out of Firecrawl",
        bodyText: "Hey Burni,\n\nWelcome to Firecrawl! Here are three quick patterns to extract pristine markdown from modern dynamic websites:\n\n1. Web Search & Scraping: Use /scrape to parse javascript-heavy SPAs.\n2. Crawl & Index: Use /crawl to recursively map site trees into markdown.\n3. Research API: Extract structured JSON with schemas for AI agents.\n\nLet us know if you need custom rate limits or dedicated proxy pools!\n\nCheers,\nAlex Nurzi\nCo-Founder, Firecrawl",
        status: "received",
        agentSuggestedReply: "Hi Alex,\n\nThank you for reaching out! We've already integrated Firecrawl MCP into our OmniDome AI agent orchestrator pipeline.\n\nBest,\nBurni",
        createdAt: "2026-09-27T00:56:00Z",
      },
    ],
  },

  // 2. Benedict Majozi - Exact match from screenshot media_1790515130371.png
  {
    id: "thread-benedict-test",
    podId: "pod-default",
    mailboxId: "mb-burnibraa",
    sender: "Benedict Majozi",
    senderEmail: "benemajozl@gmail.com",
    recipientEmail: "burnibraa@agentmail.to",
    subject: "Test",
    snippet: "Test Regards Benedict Sibusiso Majozi 0832124858 (c)",
    unread: false,
    isStarred: false,
    folder: "inbox",
    labels: ["Verified Senders", "Test"],
    assignedAgent: "auto_reply",
    messagesCount: 1,
    hasAttachments: false,
    dateGroup: "Sep 7",
    timestamp: "7:39 AM",
    aiAnalysis: {
      sentiment: "neutral",
      category: "Connectivity Verification",
      confidence: 0.99,
      suggestedAction: "auto_reply",
      notes: "Inbound mailbox connectivity verified successfully from Gmail relay.",
    },
    messages: [
      {
        id: "msg-ben-1",
        threadId: "thread-benedict-test",
        direction: "inbound",
        sender: "Benedict Majozi",
        senderEmail: "benemajozl@gmail.com",
        recipient: "Burni Braai",
        recipientEmail: "burnibraa@agentmail.to",
        subject: "Test",
        bodyText: "Test\n\nRegards\nBenedict Sibusiso Majozi\n0832124858 (c)",
        status: "received",
        agentSuggestedReply: "Hi Benedict,\n\nTest transmission received successfully by AgentMail on pod-default.\n\nBest regards,\nOmniDome AI Agent",
        createdAt: "2026-09-07T05:39:00Z",
      },
    ],
  },

  // 3. mailer-daemon failure 1 - Exact match from screenshot media_1790515130371.png
  {
    id: "thread-bounce-1",
    podId: "pod-default",
    mailboxId: "mb-burnibraa",
    sender: "mailer-daemon@agentmail.to",
    senderEmail: "mailer-daemon@agentmail.to",
    recipientEmail: "burnibraa@agentmail.to",
    subject: "Delivery Status Notification (Failure)",
    snippet: "An error occurred while trying to deliver your email: 550 5.1.1 The email account that you tried to reach does not exist.",
    unread: false,
    isStarred: false,
    folder: "inbox",
    labels: ["System Bounce", "Bounced"],
    assignedAgent: "auto_reply",
    messagesCount: 1,
    hasAttachments: false,
    dateGroup: "Aug 29",
    timestamp: "7:16 PM",
    aiAnalysis: {
      sentiment: "negative",
      category: "Delivery Failure (Bounce)",
      confidence: 1.0,
      suggestedAction: "none",
      notes: "Remote MTA rejected recipient majozippe@gmail.com. Automatically added to Send Block List.",
    },
    messages: [
      {
        id: "msg-bounce-1",
        threadId: "thread-bounce-1",
        direction: "inbound",
        sender: "mailer-daemon@agentmail.to",
        senderEmail: "mailer-daemon@agentmail.to",
        recipient: "Burni Braai",
        recipientEmail: "burnibraa@agentmail.to",
        subject: "Delivery Status Notification (Failure)",
        bodyText: "Delivery Status Notification (Failure)\n\nAn error occurred while trying to deliver your email to majozippe@gmail.com:\n550-5.1.1 The email account that you tried to reach does not exist. Please try double-checking the recipient's email address for typos or unnecessary spaces.\n\nStatus: 5.1.1 (Permanent Failure - Bad Destination Mailbox Address)\nDiagnostic-Code: smtp; 550-5.1.1 recipient not found",
        status: "received",
        createdAt: "2026-08-29T17:16:00Z",
      },
    ],
  },

  // 4. mailer-daemon failure 2 - Exact match from screenshot
  {
    id: "thread-bounce-2",
    podId: "pod-default",
    mailboxId: "mb-burnibraa",
    sender: "mailer-daemon@agentmail.to",
    senderEmail: "mailer-daemon@agentmail.to",
    recipientEmail: "burnibraa@agentmail.to",
    subject: "Delivery Status Notification (Failure)",
    snippet: "An error occurred while trying to deliver your email: 550 5.1.1 Destination address rejected by remote host.",
    unread: false,
    isStarred: false,
    folder: "inbox",
    labels: ["System Bounce", "Bounced"],
    assignedAgent: "auto_reply",
    messagesCount: 1,
    hasAttachments: false,
    dateGroup: "Aug 29",
    timestamp: "7:15 PM",
    aiAnalysis: {
      sentiment: "negative",
      category: "Delivery Failure (Bounce)",
      confidence: 1.0,
      suggestedAction: "none",
      notes: "Remote MTA retry timeout. Address quarantined.",
    },
    messages: [
      {
        id: "msg-bounce-2",
        threadId: "thread-bounce-2",
        direction: "inbound",
        sender: "mailer-daemon@agentmail.to",
        senderEmail: "mailer-daemon@agentmail.to",
        recipient: "Burni Braai",
        recipientEmail: "burnibraa@agentmail.to",
        subject: "Delivery Status Notification (Failure)",
        bodyText: "Delivery Status Notification (Failure)\n\nRemote MTA responded with error code 550 5.1.1. Outbound envelope halted.",
        status: "received",
        createdAt: "2026-08-29T17:15:00Z",
      },
    ],
  },

  // 5. mailer-daemon failure 3 - Exact match from screenshot
  {
    id: "thread-bounce-3",
    podId: "pod-default",
    mailboxId: "mb-burnibraa",
    sender: "mailer-daemon@agentmail.to",
    senderEmail: "mailer-daemon@agentmail.to",
    recipientEmail: "burnibraa@agentmail.to",
    subject: "Delivery Status Notification (Failure)",
    snippet: "An error occurred while trying to deliver your email: 550 5.1.1 Recipient mailbox unavailable.",
    unread: false,
    isStarred: false,
    folder: "inbox",
    labels: ["System Bounce", "Bounced"],
    assignedAgent: "auto_reply",
    messagesCount: 1,
    hasAttachments: false,
    dateGroup: "Aug 29",
    timestamp: "7:15 PM",
    aiAnalysis: {
      sentiment: "negative",
      category: "Delivery Failure (Bounce)",
      confidence: 1.0,
      suggestedAction: "none",
      notes: "Automated bounce triage logged.",
    },
    messages: [
      {
        id: "msg-bounce-3",
        threadId: "thread-bounce-3",
        direction: "inbound",
        sender: "mailer-daemon@agentmail.to",
        senderEmail: "mailer-daemon@agentmail.to",
        recipient: "Burni Braai",
        recipientEmail: "burnibraa@agentmail.to",
        subject: "Delivery Status Notification (Failure)",
        bodyText: "Delivery Status Notification (Failure)\n\nRemote recipient address rejected.",
        status: "received",
        createdAt: "2026-08-29T17:15:00Z",
      },
    ],
  },

  // 6. Sales Agent thread: High-value enterprise lead
  {
    id: "thread-sales-2",
    podId: "pod-default",
    mailboxId: "mb-sales",
    sender: "Naledi Khumalo",
    senderEmail: "nkhumalo@apexlogistics.co.za",
    recipientEmail: "sales@omnidome.co.za",
    subject: "Enterprise Telemetry & Fleet Integration Inquiry (500 Nodes)",
    snippet: "Good day Sales Team, We are exploring OmniDome's IoT and communication platform for our logistics fleet across Gauteng. Could you provide a formal quote and trial access?",
    unread: true,
    isStarred: true,
    folder: "inbox",
    labels: ["Sales Inquiry", "High Intent", "Smart Labeled"],
    assignedAgent: "sales",
    messagesCount: 2,
    hasAttachments: true,
    dateGroup: "Today",
    timestamp: "10:15 AM",
    aiAnalysis: {
      sentiment: "positive",
      category: "Sales Lead - Enterprise Tier",
      confidence: 0.96,
      suggestedAction: "request_approval",
      leadScore: 92,
      quoteAmount: "R 245,000 / yr",
      notes: "High-intent lead. Sales Agent analyzed payload and drafted enterprise proposal with 15% introductory discount. Requires human approval before final dispatch.",
    },
    messages: [
      {
        id: "msg-2a",
        threadId: "thread-sales-2",
        direction: "inbound",
        sender: "Naledi Khumalo",
        senderEmail: "nkhumalo@apexlogistics.co.za",
        recipient: "Sales Agent",
        recipientEmail: "sales@omnidome.co.za",
        subject: "Enterprise Telemetry & Fleet Integration Inquiry (500 Nodes)",
        bodyText: "Good day Sales Team,\n\nWe are looking to transition our 500-vehicle telematics telemetry onto OmniDome. Can you outline pricing for real-time telemetry, automated driver alerts, and SLA guarantee?\n\nAttached is our current fleet spec sheet.\n\nWarm regards,\nNaledi Khumalo\nHead of Operations | Apex Logistics",
        attachments: [
          {
            id: "att-1",
            filename: "Apex_Fleet_Specs_Q3.pdf",
            sizeBytes: 428000,
            mimeType: "application/pdf",
          },
        ],
        status: "received",
        createdAt: "2026-09-27T08:15:00Z",
      },
      {
        id: "msg-2b",
        threadId: "thread-sales-2",
        direction: "outbound",
        sender: "Sales Agent (OmniDome)",
        senderEmail: "sales@omnidome.co.za",
        recipient: "Naledi Khumalo",
        recipientEmail: "nkhumalo@apexlogistics.co.za",
        subject: "Re: Enterprise Telemetry & Fleet Integration Inquiry (500 Nodes)",
        bodyText: "Dear Naledi,\n\nThank you for considering OmniDome. Our IoT gateway seamlessly accommodates 500+ active edge nodes with sub-50ms telemetry routing.\n\nI have prepared a draft customized deployment schedule and tailored enterprise quote. Our team lead Sarah Chen is currently reviewing the customized terms.",
        status: "draft",
        agentResponse: "Sales proposal prepared. Awaiting discount approval.",
        createdAt: "2026-09-27T08:18:00Z",
      },
    ],
  },

  // 7. Smart Label Agent thread: Support & Incident report
  {
    id: "thread-info-3",
    podId: "pod-default",
    mailboxId: "mb-info",
    sender: "David Mthembu",
    senderEmail: "david@mthembubuilders.com",
    recipientEmail: "info@omnidome.co.za",
    subject: "Fibre gateway connection drops intermittently after storm",
    snippet: "Hello, our central branch router has been rebooting since yesterday's lightning storm. Is there an active ticket or technician coming out?",
    unread: true,
    isStarred: false,
    folder: "inbox",
    labels: ["Support", "Urgent", "Smart Labeled"],
    assignedAgent: "smart_label",
    messagesCount: 1,
    hasAttachments: false,
    dateGroup: "Today",
    timestamp: "11:42 AM",
    aiAnalysis: {
      sentiment: "urgent",
      category: "Technical Incident - Network",
      confidence: 0.94,
      suggestedAction: "escalate",
      notes: "Smart Label Agent identified critical hardware fault following storm. Auto-classified as Urgent Support and routed alert to Network Operations.",
    },
    messages: [
      {
        id: "msg-3",
        threadId: "thread-info-3",
        direction: "inbound",
        sender: "David Mthembu",
        senderEmail: "david@mthembubuilders.com",
        recipient: "Smart Label Agent (Info)",
        recipientEmail: "info@omnidome.co.za",
        subject: "Fibre gateway connection drops intermittently after storm",
        bodyText: "Hello,\n\nOur central branch router has been rebooting since yesterday's lightning storm. We cannot process warehouse orders right now. Could someone urgently inspect the optical line or swap the gateway?\n\nAccount #: OM-88391\nLocation: Midrand Industrial Park",
        status: "received",
        agentSuggestedReply: "Hi David,\n\nWe have logged Ticket #INC-9402 regarding the Midrand Industrial Park optical connection drops. Our Field Service team has been dispatched and will reach you within 90 minutes.",
        createdAt: "2026-09-27T09:42:00Z",
      },
    ],
  },

  // 8. Finance Agent thread: Invoice query
  {
    id: "thread-finance-4",
    podId: "pod-default",
    mailboxId: "mb-finance",
    sender: "Accounts Payable",
    senderEmail: "accounts@vodacom-partner.co.za",
    recipientEmail: "finance@omnidome.co.za",
    subject: "Remittance Advice - Sept 2026 Wholesale Settlement",
    snippet: "Attached please find payment remittance for invoice INV-2026-0901.",
    unread: false,
    isStarred: false,
    folder: "inbox",
    labels: ["Billing", "Settlement", "Smart Labeled"],
    assignedAgent: "finance",
    messagesCount: 1,
    hasAttachments: true,
    dateGroup: "Yesterday",
    timestamp: "4:20 PM",
    aiAnalysis: {
      sentiment: "neutral",
      category: "Accounts Receivable",
      confidence: 0.98,
      suggestedAction: "create_task",
      quoteAmount: "R 84,200.00",
      notes: "Finance Agent extracted remittance advice total of R84,200. Reconciled against ledger automatically.",
    },
    messages: [
      {
        id: "msg-4",
        threadId: "thread-finance-4",
        direction: "inbound",
        sender: "Accounts Payable",
        senderEmail: "accounts@vodacom-partner.co.za",
        recipient: "Finance Agent",
        recipientEmail: "finance@omnidome.co.za",
        subject: "Remittance Advice - Sept 2026 Wholesale Settlement",
        bodyText: "Good day,\n\nPlease find attached the remittance statement for EFT transfer completed this afternoon.\nRef: INV-2026-0901\nAmount: R84,200.00",
        attachments: [
          {
            id: "att-2",
            filename: "Remittance_Advice_INV0901.pdf",
            sizeBytes: 184000,
            mimeType: "application/pdf",
          },
        ],
        status: "processed",
        createdAt: "2026-09-26T14:20:00Z",
      },
    ],
  },
]

export const INITIAL_LABELS: AgentMailLabel[] = [
  { id: "lbl-sales", name: "Sales Inquiry", color: "bg-emerald-500/20 text-emerald-400 border-emerald-500/30", count: 18 },
  { id: "lbl-support", name: "Support", color: "bg-blue-500/20 text-blue-400 border-blue-500/30", count: 24 },
  { id: "lbl-urgent", name: "Urgent", color: "bg-red-500/20 text-red-400 border-red-500/30", count: 4 },
  { id: "lbl-billing", name: "Billing", color: "bg-purple-500/20 text-purple-400 border-purple-500/30", count: 9 },
  { id: "lbl-smart", name: "Smart Labeled", color: "bg-cyan-500/20 text-cyan-400 border-cyan-500/30", count: 37 },
  { id: "lbl-approval", name: "Approval Needed", color: "bg-amber-500/20 text-amber-400 border-amber-500/30", count: 3 },
]

export const INITIAL_LIST_RULES: AgentMailListRule[] = [
  {
    id: "rule-1",
    podId: "pod-default",
    type: "allow",
    pattern: "*@omnidome.co.za",
    target: "domain",
    reason: "Internal organization domain - always bypass spam filters",
    createdAt: "2026-08-15T00:00:00Z",
  },
  {
    id: "rule-2",
    podId: "pod-default",
    type: "allow",
    pattern: "benemajozl@gmail.com",
    target: "email",
    reason: "Executive & Founder test address",
    createdAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "rule-3",
    podId: "pod-default",
    type: "block",
    pattern: "majozippe@gmail.com",
    target: "email",
    reason: "Bounced",
    createdAt: "2026-08-29T17:16:00Z",
  },
  {
    id: "rule-4",
    podId: "pod-default",
    type: "block",
    pattern: "*@marketing-spammers-bot.net",
    target: "domain",
    reason: "Automated phishing & cold scraper list",
    createdAt: "2026-09-02T00:00:00Z",
  },
]

export const INITIAL_DOMAINS: AgentMailDomain[] = [
  {
    id: "dom-omnidome",
    podId: "pod-default",
    domain: "omnidome.co.za",
    status: "verified",
    mxValid: true,
    spfValid: true,
    dkimValid: true,
    dmarcValid: true,
    dnsRecords: [
      { type: "MX", host: "@", value: "feedback-smtp.agentmail.to (Priority 10)", status: "valid" },
      { type: "TXT", host: "@", value: "v=spf1 include:mail.agentmail.to ~all", status: "valid" },
      { type: "CNAME", host: "agentmail._domainkey", value: "dkim.agentmail.to", status: "valid" },
      { type: "TXT", host: "_dmarc", value: "v=DMARC1; p=reject; rua=mailto:dmarc@omnidome.co.za", status: "valid" },
    ],
    createdAt: "2026-08-10T12:00:00Z",
  },
  {
    id: "dom-agentmail",
    podId: "pod-default",
    domain: "agentmail.to",
    status: "verified",
    mxValid: true,
    spfValid: true,
    dkimValid: true,
    dmarcValid: true,
    dnsRecords: [
      { type: "MX", host: "@", value: "inbound.agentmail.to", status: "valid" },
    ],
    createdAt: "2026-08-01T00:00:00Z",
  },
]

// 30-day message activity matrix with 55 total messages matching media_1790515187100.png
export const INITIAL_METRICS: AgentMailMetrics & {
  sentCount: number
  receivedCount: number
  bouncedCount: number
  rejectedCount: number
  complainedCount: number
  bounceRate: number
  complaintRate: number
  streakDays: number
  messages30Days: number
  activityMatrix: { date: string; dayOfWeek: number; count: number; level: number }[]
} = {
  totalInbound: 33,
  totalOutbound: 22,
  automatedRepliesSent: 18,
  avgResponseSeconds: 1.8,
  smartLabelAccuracy: 97.4,
  pendingApprovals: 3,
  escalatedToHuman: 6,
  activeAgents: 4,
  deliveryRate: 88.0,
  sentCount: 22,
  receivedCount: 33,
  bouncedCount: 3,
  rejectedCount: 0,
  complainedCount: 0,
  bounceRate: 12.0,
  complaintRate: 0.0,
  streakDays: 3,
  messages30Days: 55,
  volumeByHour: [
    { hour: "08:00", inbound: 5, outbound: 3 },
    { hour: "09:00", inbound: 12, outbound: 8 },
    { hour: "10:00", inbound: 8, outbound: 6 },
    { hour: "11:00", inbound: 4, outbound: 3 },
    { hour: "12:00", inbound: 2, outbound: 1 },
    { hour: "13:00", inbound: 1, outbound: 1 },
    { hour: "14:00", inbound: 1, outbound: 0 },
  ],
  categoryDistribution: [
    { category: "Sales Inquiries", count: 18, percentage: 32.7 },
    { category: "Customer Support", count: 16, percentage: 29.1 },
    { category: "System & Verification", count: 12, percentage: 21.8 },
    { category: "Bounces & Failures", count: 6, percentage: 10.9 },
    { category: "Billing & Settlement", count: 3, percentage: 5.5 },
  ],
  // 30 days grid of heatmap cells (0 = empty, 1 = 1-3, 2 = 4-7, 3 = 8+)
  activityMatrix: [
    { date: "Aug 29", dayOfWeek: 5, count: 8, level: 3 },
    { date: "Aug 30", dayOfWeek: 6, count: 2, level: 1 },
    { date: "Aug 31", dayOfWeek: 0, count: 0, level: 0 },
    { date: "Sep 01", dayOfWeek: 1, count: 4, level: 2 },
    { date: "Sep 02", dayOfWeek: 2, count: 1, level: 1 },
    { date: "Sep 03", dayOfWeek: 3, count: 0, level: 0 },
    { date: "Sep 04", dayOfWeek: 4, count: 0, level: 0 },
    { date: "Sep 05", dayOfWeek: 5, count: 5, level: 2 },
    { date: "Sep 06", dayOfWeek: 6, count: 1, level: 1 },
    { date: "Sep 07", dayOfWeek: 0, count: 9, level: 3 },
    { date: "Sep 08", dayOfWeek: 1, count: 2, level: 1 },
    { date: "Sep 09", dayOfWeek: 2, count: 0, level: 0 },
    { date: "Sep 10", dayOfWeek: 3, count: 3, level: 1 },
    { date: "Sep 11", dayOfWeek: 4, count: 0, level: 0 },
    { date: "Sep 12", dayOfWeek: 5, count: 2, level: 1 },
    { date: "Sep 13", dayOfWeek: 6, count: 0, level: 0 },
    { date: "Sep 14", dayOfWeek: 0, count: 0, level: 0 },
    { date: "Sep 15", dayOfWeek: 1, count: 1, level: 1 },
    { date: "Sep 16", dayOfWeek: 2, count: 0, level: 0 },
    { date: "Sep 17", dayOfWeek: 3, count: 2, level: 1 },
    { date: "Sep 18", dayOfWeek: 4, count: 1, level: 1 },
    { date: "Sep 19", dayOfWeek: 5, count: 0, level: 0 },
    { date: "Sep 20", dayOfWeek: 6, count: 0, level: 0 },
    { date: "Sep 21", dayOfWeek: 0, count: 0, level: 0 },
    { date: "Sep 22", dayOfWeek: 1, count: 1, level: 1 },
    { date: "Sep 23", dayOfWeek: 2, count: 0, level: 0 },
    { date: "Sep 24", dayOfWeek: 3, count: 0, level: 0 },
    { date: "Sep 25", dayOfWeek: 4, count: 3, level: 1 },
    { date: "Sep 26", dayOfWeek: 5, count: 4, level: 2 },
    { date: "Sep 27", dayOfWeek: 6, count: 6, level: 3 },
  ],
}

export const INITIAL_PERMISSIONS: AgentMailPermission[] = [
  {
    id: "perm-1",
    role: "admin",
    userEmail: "burnibraa@gmail.com",
    userName: "Burni Braai",
    inboxAccess: "all",
    canSend: true,
    canConfigureAgents: true,
    canApproveQuotes: true,
  },
  {
    id: "perm-2",
    role: "admin",
    userEmail: "benedict@omnidome.co.za",
    userName: "Benedict S. Majozi",
    inboxAccess: "all",
    canSend: true,
    canConfigureAgents: true,
    canApproveQuotes: true,
  },
  {
    id: "perm-3",
    role: "operator",
    userEmail: "sarah.chen@omnidome.co.za",
    userName: "Sarah Chen",
    inboxAccess: ["sales@omnidome.co.za"],
    canSend: true,
    canConfigureAgents: false,
    canApproveQuotes: true,
  },
]
