ARG BASE_IMAGE
FROM ${BASE_IMAGE}
ARG SERVICE_NAME
COPY services/common/ /app/services/common/
COPY services/${SERVICE_NAME}/ /app/services/${SERVICE_NAME}/
RUN if [ "$SERVICE_NAME" = "inventory" ]; then pip install --no-cache-dir 'reportlab>=4,<5'; fi
